[alias]
coverage = "llvm-cov --ignore-filename-regex=log|bin/bonka"
coverage-html = "llvm-cov --ignore-filename-regex=log|bin/bonka --html"
coverage-text = "llvm-cov --ignore-filename-regex=log|bin/bonka --text"
