[package]
name = "bonka"
version = "0.1.0"
edition = "2024"
authors = ["Zack Kollar (SeedyROM)"]

[dependencies]
bonka-server = { path = "../../bonka" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }

[lib]
name = "bonka_client"
path = "src/lib.rs"
